branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '8'
before_install:
- mkdir -p ../node_modules
- ln -s -T `pwd` ../node_modules/thingpedia
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
env:
  global:
    secure: L6XZjIB7I9fZ01h75PE9ydwhHIAi+GgnfIeKzdylwopgT5Mu00uB+EDGuHZMb0Do8SVfHeeTuHVR/RUlKcqcVv5oZI1FFY5ZJz1vdAx4nqW38FC1cHUtBS83aN1BpjUx/Wk2qscTJV7twUTvHrgPRT0Um6trtud0Kt9IDGbXnxH4LPaHhJ4t6Xs9fF53LVTQCV4tJfBi4n836dcm82siuuQw7NFSKwk2hhv55XXQvTOq4zEK8cTCadZWqzbLxu2TPLdlVEgqNAXi1S8T04Dy+QDnxcHRBkCzh9JsxMxMhNZKWOZQYZHXgKStTvZvSFb6K7U8oK5KziTXYN9V0SUK4BoPV3eBDJLo5tI7CUSZSqsk4j0VFd3gC3VHmDRmTFH0nlo7eVKjFmeHp8qc/vg5eKNRzkH6DcXQxgjOBuZS2/n1X2upsz1NC9XF18QpUbN0GXfnEoFH6jmdvFao4RWurWBWoYANDEkzd/MRhYWoCUpCGX6nIscc5aEAAmEVFyX3woM/aEoxmUSdzwAuT3ylDQdIsscWtQxCboFoKK4z6G/nxyxYSm+1Wm2K7sxc/BrqVcZ0cx8ounjr9EMBvmVZ9BYxjJPzlWci0mO27H+PJNyBR6VS/waYy86yPtt/TZIIYQ75jID3WEnRjsot+KfVpax7rHoSmk3bCt5bQGooupU=
deploy:
  provider: npm
  email: gcampagn@cs.stanford.edu
  api_key:
    secure: H38R+MzxxeLLfy32V8MCZJBVXC0rhtahaKCU+GXtawb6uMgwqS+Q4cYYrcjtAHDFXjVXGtDqMOlyDRYpMbp7BpIyelhhQCywHEhhmzetnswFhW4I2JFRT2woNEM9TKwMnRx/cP1MI69THnvcl+m6fYykVKluW/0ZoT5ATu7vcLWBJR0lJvOwdpdAZVXK2GVrEKMnJWjdt/223XNCGhMH+WaDrTo+ikebEcKoBl0P96EsFNytTrzcrxvwcomjhWYo5t3D2IecU/8gT6gKDelSOlmRuBSTgeGShH5H2a/iP4DGRu+UEMcuo9h8G/l/c8axIakVMc1FVN5d5XaWqoFJp5ola4GSOACxKdiLXift0zchHyakfXBbGx4PNVaJbBibztRkw9jqExDxDYeCCqbDaqcsNwy3vJhtwtPxGG5/oXeLP/nQkxMHhq+zYbdGCOUwkYlhy/0fWhNyXqCEOB+DN7rxMBjklOM/W2jSbUvjJK+N+60LP6WXHuJRqO8lgIAcokKkw9V1Qh2htJOnJF8fCWxzi7RYs8fu5r9Pr+tc+9MnJOQ0jLW8Se9WNpOSDHN4GgguAYyhd3o3T8beUTmdoETZEbP3Klqhuby62jXm3qkMZZMUtZzbDXbkvZ1JrkQ6U9FVZTegA/ZRqxIQ6aAuxa3dkfFA/sSzr6csDXj9c1Q=
  on:
    tags: true
    repo: Stanford-Mobisocial-IoT-Lab/thingpedia-api
