branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '10'
before_install:
- mkdir -p ../node_modules
- ln -s -T `pwd` ../node_modules/thingpedia
script:
- npm run lint
- TZ="America/Los_Angeles" npm run test
after_success: npm run coverage
env:
  global:
  - COVERALLS_PARALLEL=true
deploy:
  provider: npm
  email: gcampagn@cs.stanford.edu
  skip_cleanup: true
  api_key:
    secure: H38R+MzxxeLLfy32V8MCZJBVXC0rhtahaKCU+GXtawb6uMgwqS+Q4cYYrcjtAHDFXjVXGtDqMOlyDRYpMbp7BpIyelhhQCywHEhhmzetnswFhW4I2JFRT2woNEM9TKwMnRx/cP1MI69THnvcl+m6fYykVKluW/0ZoT5ATu7vcLWBJR0lJvOwdpdAZVXK2GVrEKMnJWjdt/223XNCGhMH+WaDrTo+ikebEcKoBl0P96EsFNytTrzcrxvwcomjhWYo5t3D2IecU/8gT6gKDelSOlmRuBSTgeGShH5H2a/iP4DGRu+UEMcuo9h8G/l/c8axIakVMc1FVN5d5XaWqoFJp5ola4GSOACxKdiLXift0zchHyakfXBbGx4PNVaJbBibztRkw9jqExDxDYeCCqbDaqcsNwy3vJhtwtPxGG5/oXeLP/nQkxMHhq+zYbdGCOUwkYlhy/0fWhNyXqCEOB+DN7rxMBjklOM/W2jSbUvjJK+N+60LP6WXHuJRqO8lgIAcokKkw9V1Qh2htJOnJF8fCWxzi7RYs8fu5r9Pr+tc+9MnJOQ0jLW8Se9WNpOSDHN4GgguAYyhd3o3T8beUTmdoETZEbP3Klqhuby62jXm3qkMZZMUtZzbDXbkvZ1JrkQ6U9FVZTegA/ZRqxIQ6aAuxa3dkfFA/sSzr6csDXj9c1Q=
  on:
    tags: true
    repo: stanford-oval/thingpedia-api
notifications:
  webhooks: https://coveralls.io/webhook
  slack:
    secure: cjz76sz9UmspDtO7oLH0IjXcAeMkefVwopYABMvPY7bLDQEBv14pkuRL4yCjh5fVIIzMHQJSNzv5b8DmH2O4dJ1ko1YOx/iLtU0GOcOZvWe6OLY9X4zuqJPLIqOaLL3rQMSTHTGiVdI8jBEv0uCJ4C0jYNsmnzdtG1kB5Iaovx36sRNP9B+iCoQGDi755bM4iVCymCr7vKKg9VZRVHIPLkD0ortBuXdL5CAzNigfilecwLMPEJWnOp3boFBdCu9/6lAQbAHEMZkHH8jxHfCQmyWT5azGFgarphkobXRsl25aCG9wo1Z0wOmLTOH8pXKK7HqVrjPkFNtWTAQdGtIvFv5Fd/7CTZf02g8gx2ulZIGFgZZGjt9jqReuh5ZS27swoGoiRNmWvdlkxGbCVKLjhvkwxqKovaklRQt1RF11T0r3isEXtexFdOlY5QdRGF0LdQxGnnaq7q4FpJU2Wkx5o5ugnxIxl+VMxTBDWQRvdbfCVQFXVcLzS68WUHC5h2D4QsXidlovRg113T/iM4j2IajaRW7O9D80HTUvpgeR7S1Q3Xe8Ae68CDXqh4kQDttbJXNL/wM7W9vgaXiTC7VNRHbQsRrlrzoiOVKyKF9GxmNlLKJJ2XkjsIKXPfzraYAD8DN0NMGOnP/li2+iSFesv7eR7lGoAKc6rYeCKoYzFWw=
