language: node_js
node_js:
- '8'
before_install:
- mkdir -p ../node_modules
- ln -s -T `pwd` ../node_modules/thingpedia
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage